### ISSUE TITLE
Unable to establish SSL connection

### ISSUE THREAD

**Issue by danielgf0824** [GT-RIPL/Xmodal-Ctx#3]
can you fix it?

**Comment by albert-cwkuo** [comment]
What do you mean by the SSL connection?

**Comment by danielgf0824** [comment]
i cant download the pre-computed context from your link

**Comment by danielgf0824** [comment]
> 

i cant download the pre-computed context from the link

**Comment by danielgf0824** [comment]
i cant download the pre-computed context from the link

**Comment by albert-cwkuo** [comment]
All links work fine on my side. Can you be more specific about which link is broken and provide the error message or screenshot?
